name: EditorConfig lint
description: Lint the files based on the .editorconfig
runs:
  using: docker
  image: Dockerfile
branding:
  icon: edit
  color: white

inputs:
  working_directory:
    required: false
    description: |
      Directory to run the action on, from the repo root.
      Default is empty, thus using git ls-files
    default: ""
  eclint_args:
    required: false
    description: |
      Space separated args specified here will be added to eclint during execution
